#!/usr/bin/env python3
"""Regenerate docs/skills.md and docs/agents.md from the skill and agent files.

Run from the repo root:  python3 tools/build_catalog.py
Run with --check in CI:  exits 1 if the docs are out of date.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "plugins" / "ludo" / "skills"
AGENTS = ROOT / "plugins" / "ludo" / "agents"

GROUPS = [
    ("Start here", ["about-me", "ask-first", "brainstorm", "plan", "short-answers", "remember", "usage-meter", "prompt-coach"]),
    ("Research and the web", ["research", "deep-research", "scrape", "whats-new", "video-notes"]),
    ("School", ["study", "explain", "paper", "cite", "second-brain"]),
    ("Career", ["resume", "job-hunt", "pitch", "idea-check"]),
    ("Finance", ["comps", "dcf", "lbo", "three-statement", "earnings", "equity-note", "stock-pitch"]),
    ("Make things", ["design", "mockup", "brand-kit", "slides", "powerpoint", "word-doc", "diagram", "spreadsheet", "pdf",
                     "video-cut", "sound-human"]),
    ("Daily life", ["morning", "journal"]),
    ("Build and ship code", ["code-carefully", "test-first", "fix-it", "code-review", "save-points", "pack-code", "autopilot",
                             "make-skill"]),
]


def frontmatter(path):
    text = path.read_text(encoding="utf-8")
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        raise SystemExit(f"{path}: missing frontmatter")
    fields = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            fields[k.strip()] = v.strip()
    return fields


def first_sentence(desc):
    s = re.split(r"(?<=[.!?])\s", desc, maxsplit=1)[0]
    return s.rstrip(".") + "."


def extras(skill_dir):
    found = []
    for sub, label in (("scripts", "script"), ("templates", "templates"), ("examples", "example"), ("reference", "reference")):
        if (skill_dir / sub).is_dir():
            found.append(label)
    return ", ".join(found)


def skills_doc():
    names = {p.parent.name for p in SKILLS.glob("*/SKILL.md")}
    grouped = {n for _, ns in GROUPS for n in ns}
    missing = sorted(names - grouped)
    if missing:
        raise SystemExit(f"Skills not in any group in tools/build_catalog.py: {missing}")
    out = ["# Skills", "",
           f"{len(names)} skills. Type the command in Claude Code, or just describe what you want and Claude picks the right skill on its own.",
           ""]
    for title, ns in GROUPS:
        out += [f"## {title}", "", "| Command | What it does | Ships with |", "|---|---|---|"]
        for n in ns:
            fm = frontmatter(SKILLS / n / "SKILL.md")
            out.append(f"| `/ludo:{n}` | {first_sentence(fm['description'])} | {extras(SKILLS / n) or '-'} |")
        out.append("")
    out.append("_This page is generated by `tools/build_catalog.py`. Edit the skills, not this file._")
    return "\n".join(out) + "\n"


def agents_doc():
    out = ["# Agents", "",
           "Agents are helpers Claude sends off to do a side job with their own fresh memory, so your main conversation stays clean. "
           "They all run on Sonnet to save your Pro limits.", "",
           "Claude uses them on its own when a task fits. You can also ask directly: \"use the researcher to find...\".", "",
           "| Agent | What it does |", "|---|---|"]
    for p in sorted(AGENTS.glob("*.md")):
        fm = frontmatter(p)
        out.append(f"| `{fm['name']}` | {first_sentence(fm['description'])} |")
    out += ["", "_This page is generated by `tools/build_catalog.py`._"]
    return "\n".join(out) + "\n"


def main():
    targets = {ROOT / "docs" / "skills.md": skills_doc(), ROOT / "docs" / "agents.md": agents_doc()}
    if "--check" in sys.argv:
        stale = [str(p.relative_to(ROOT)) for p, text in targets.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != text]
        if stale:
            print("Out of date, run python3 tools/build_catalog.py:", ", ".join(stale))
            return 1
        print("Catalog is up to date.")
        return 0
    for p, text in targets.items():
        p.parent.mkdir(exist_ok=True)
        p.write_text(text, encoding="utf-8")
        print("Wrote", p.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
